/**
 * Filename: TaskData.ts
 * Description: Task Data to enter into the Database
 * 
 * Create Date: 07 Apr 2024
 */

export const tasks = [
    // Tasks assigned in Project 1
    {
        task_id: '1',
        title: 'Create Database',
        description: 'Create the database and the required tables in it, and fill the tables with the dummy data',
        status: 'active',
        progress: 'not started',
        priority: 'high',
        story_points: '4',
        user_id: 'Z03002',
        project_id: 'PA0100',
        start_date: '2024-05-06',
        end_date: '2024-05-19',
        assigned_by: 'Z02000',
        created_by: 'Z02000',
    },
    {
        task_id: '2',
        title: 'Create Graphql Queries',
        description: 'Create the Graphql Queries to fetch the data from all the tables (individually and collectively) in the database',
        status: 'active',
        progress: 'not started',
        priority: 'high',
        story_points: '5',
        user_id: 'Z03002',
        project_id: 'PA0100',
        start_date: '2024-05-20',
        end_date: '2024-06-09',
        assigned_by: 'Z02000',
        created_by: 'Z02000',
    },
    {
        task_id: '3',
        title: 'Create Graphql Mutations',
        description: 'Create the Graphql Mutations to Insert, Update and Delete the data to all the tables individually',
        status: 'active',
        progress: 'not started',
        priority: 'high',
        story_points: '5',
        user_id: 'Z03002',
        project_id: 'PA0100',
        start_date: '2024-06-10',
        end_date: '2024-06-30',
        assigned_by: 'Z02000',
        created_by: 'Z02000',
    },
    {
        task_id: '4',
        title: 'Create Filter Queries',
        description: 'Create the Graphql Queries to fetch the data from all the tables (individually and collectively) based on the filters passed as arguments in the Queries',
        status: 'active',
        progress: 'not started',
        priority: 'high',
        story_points: '5',
        user_id: 'Z03002',
        project_id: 'PA0100',
        start_date: '2024-07-01',
        end_date: '2024-07-21',
        assigned_by: 'Z02000',
        created_by: 'Z02000',
    },

    // Tasks assigned in Project 2
    {
        task_id: '5',
        title: 'Create UI Design',
        description: 'Create the UI Design for the entire application based on the given requirements',
        status: 'active',
        progress: 'not started',
        priority: 'high',
        story_points: '5',
        user_id: 'Z03000',
        project_id: 'PA0101',
        start_date: '2024-05-06',
        end_date: '2024-05-26',
        assigned_by: 'Z02001',
        created_by: 'Z02001',
    },
    {
        task_id: '6',
        title: 'Create Login and Signup Functionality',
        description: 'Create the Login and Signup pages with all the complete functionalities like authentication, token, password-hash, session & cookies, etc.',
        status: 'active',
        progress: 'not started',
        priority: 'high',
        story_points: '5',
        user_id: 'Z03001',
        project_id: 'PA0101',
        start_date: '2024-05-27',
        end_date: '2024-06-23',
        assigned_by: 'Z02001',
        created_by: 'Z02001',
    },
    {
        task_id: '7',
        title: 'Create User Dashboard',
        description: 'Create the User Dashboard where the user would be seeing all the data related to his/her profile, projects ad tasks',
        status: 'active',
        progress: 'not started',
        priority: 'high',
        story_points: '5',
        user_id: 'Z03004',
        project_id: 'PA0101',
        start_date: '2024-05-27',
        end_date: '2024-06-23',
        assigned_by: 'Z02001',
        created_by: 'Z02001',
    },
    {
        task_id: '8',
        title: 'Add Queries',
        description: 'Add the Queries in files so that a User can fetch all the data from the server based on the requirements',
        status: 'active',
        progress: 'not started',
        priority: 'high',
        story_points: '4',
        user_id: 'Z03001',
        project_id: 'PA0101',
        start_date: '2024-06-24',
        end_date: '2024-07-14',
        assigned_by: 'Z02001',
        created_by: 'Z02001',
    },
    {
        task_id: '9',
        title: 'Add Mutations',
        description: 'Add the Mutations in the files so that a User can insert, delete and update the data on server from the Front end',
        status: 'active',
        progress: 'not started',
        priority: 'high',
        story_points: '4',
        user_id: 'Z03004',
        project_id: 'PA0101',
        start_date: '2024-06-24',
        end_date: '2024-07-14',
        assigned_by: 'Z02001',
        created_by: 'Z02001',
    },
];