// User Data to enter into the Database
export const users = [
    { 
        user_id: 'Z00100',
        first_name: "Shreya",
        last_name: "Ghosal",
        email: "shreyag@zcorp.com",
        password: "shreyag@123",
        type_id: 'PROMAN',
    },
    { 
        user_id: 'Z01000',
        first_name: "Sunidhi",
        last_name: "Chauhan",
        email: "sunidhic@zcorp.com",
        password: "sunidhic@123",
        type_id: 'PROLEAD',
    },
    { 
        user_id: 'Z01300',
        first_name: "Apoorva",
        last_name: "Deeksha",
        email: "apoorvad@zcorp.com",
        password: "apoorvad@123",
        type_id: 'DESG',
    },
    { 
        user_id: 'Z01450',
        first_name: "Priya",
        last_name: "Desai",
        email: "priyad@zcorp.com",
        password: "priyad@123",
        type_id: 'FRENG',
    },
    { 
        user_id: 'Z01200',
        first_name: "Neelam",
        last_name: "Pandey",
        email: "neelamp@zcorp.com",
        password: "neelamp@123",
        type_id: 'TSTR',
    },
    { 
        user_id: 'Z00570',
        first_name: "Trisha",
        last_name: "Singh",
        email: "trishas@zcorp.com",
        password: "trishas@123",
        type_id: 'BAENG',
    },
    { 
        user_id: 'Z00980',
        first_name: "Madhu",
        last_name: "Shree",
        email: "madhus@zcorp.com",
        password: "madhus@123",
        type_id: 'BAENG',
    },
    { 
        user_id: 'Z01069',
        first_name: "Raksha",
        last_name: "Babu",
        email: "rakshab@zcorp.com",
        password: "rakshab@123",
        type_id: 'BAENG',
    },
    {
        user_id: "Z02000",
        first_name: "Anukriti",
        last_name: "Tripathi",
        email: "anukritit@zcorp.com",
        password: "anukritit@123",
        type_id: "PROLEAD",
      }
];