/**
 * Filename: UserData.ts
 * Description: User Data to enter into the Database
 * 
 * Create Date: 29 Mar 2024
 */

export const users = [
    {
        user_id: 'Z00007',
        first_name: "Anmol",
        last_name: "Singh",
        email: "singhanmol108@zcorp.com",
        password: "anZcorSin@108",
        role_id: 'ADMN',
        created_by: 'Z00007',
    },
    { 
        user_id: 'Z01000',
        first_name: "Raksha",
        last_name: "Babu",
        email: "rakshab@zcorp.com",
        password: "rakshab@123",
        role_id: 'PRMN',
        created_by: 'Z00007',
    },
    {
        user_id: 'Z02000',
        first_name: "Apoorva",
        last_name: "Deeksha",
        email: "apoorvad@zcorp.com",
        password: "apoorvad@123",
        role_id: 'PRLE',
        created_by: 'Z00007',
    },
    { 
        user_id: 'Z02001',
        first_name: "Puja",
        last_name: "Kumari",
        email: "pujak@zcorp.com",
        password: "pujak@123",
        role_id: 'PRLE',
        created_by: 'Z00007',
    },
    { 
        user_id: 'Z02002',
        first_name: "Vannie",
        last_name: "Dogra",
        email: "vaniied@zcorp.com",
        password: "vaniied@123",
        role_id: 'PRLE',
        created_by: 'Z00007',
    },
    {
        user_id: 'Z03000',
        first_name: "Akansha",
        last_name: "Tanwar",
        email: "akanshat@zcorp.com",
        password: "akanshat@123",
        role_id: 'DESG',
        created_by: 'Z00007',
    },
    { 
        user_id: 'Z03001',
        first_name: "Surbhi",
        last_name: "Dalal",
        email: "surbhid@zcorp.com",
        password: "surbhid@123",
        role_id: 'DVPR',
        created_by: 'Z00007',
    },
    { 
        user_id: 'Z03002',
        first_name: "Madhu",
        last_name: "Shree",
        email: "madhus@zcorp.com",
        password: "madhus@123",
        role_id: 'DVPR',
        created_by: 'Z00007',
    },
    { 
        user_id: 'Z03003',
        first_name: "Shreya",
        last_name: "Bhatt",
        email: "shreyab@zcorp.com",
        password: "shreyab@123",
        role_id: 'DVPR',
        created_by: 'Z00007',
    },
    { 
        user_id: 'Z03004',
        first_name: "Nandhini",
        last_name: "Natrajan",
        email: "nandhinin@zcorp.com",
        password: "nandhinin@123",
        role_id: 'DVPR',
        created_by: 'Z00007',
    },
    {
        user_id: "Z04000",
        first_name: "Anukriti",
        last_name: "Tripathi",
        email: "anukritit@zcorp.com",
        password: "anukritit@123",
        role_id: "TSTR",
        created_by: 'Z00007',
    },
    {
        user_id: "Z04001",
        first_name: "Meghna",
        last_name: "Gowda",
        email: "meghnag@zcorp.com",
        password: "meghnag@123",
        role_id: "VLDR",
        created_by: 'Z00007',
    },
    {
        user_id: "Z05000",
        first_name: "Anu",
        last_name: "Shree",
        email: "anushree@zcorp.com",
        password: "anushree@123",
        role_id: "SPRT",
        created_by: 'Z00007',
    }
];